import { IProperty } from "../types/property";

export const properties: IProperty[] = [
  {
    id: '1',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '2',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '3',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '4',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '5',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '6',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '7',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '8',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '9',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '10',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '11',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '12',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '13',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '14',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '15',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '16',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '17',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '18',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '19',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '20',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '21',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '22',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '23',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '24',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '25',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '26',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '27',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '28',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '29',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '30',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '31',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '32',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '33',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '34',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '35',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '36',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '37',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '38',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '39',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '40',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '41',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '42',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '43',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '44',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '45',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '46',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '47',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '48',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '49',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '50',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '51',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '52',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '53',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '54',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
  {
    id: '55',
    type: 'Penthouse',
    status: 'For Rent',
    title: 'Luxury Downtown Penthouse',
    description: 'A luxurious penthouse with a breathtaking view.',
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    currency: '£',
    price: 5000,
    discount_price: 4800,
    before_price: '',
    after_price: '',
    latitude: 35.689487,
    longitude: 139.691711,
    area: 200,
    exterior_area: 50,
    country: 'Japan',
    state: 'Tokyo',
    city: 'Tokyo',
    address: '1010 Skyscraper St, Tokyo',
    zip_code: '',
    ref_id: 'REF005',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '56',
    type: 'House',
    status: 'For Sale',
    title: 'Modern Family Home',
    description: 'A beautiful modern house perfect for families.',
    rooms: 5,
    bedrooms: 3,
    bathrooms: 2,
    currency: '£',
    price: 550000,
    discount_price: 500000,
    before_price: '',
    after_price: '',
    latitude: 51.509865,
    longitude: -0.118092,
    area: 180,
    exterior_area: 50,
    country: 'United Kingdom',
    state: 'London',
    city: 'London',
    address: '123 Main St, London',
    zip_code: 'SW1A 1AA',
    ref_id: 'REF001',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '57',
    type: 'Apartment',
    status: 'For Rent',
    title: 'Cozy City Apartment',
    description: 'A cozy apartment located in the heart of the city.',
    rooms: 3,
    bedrooms: 2,
    bathrooms: 1,
    currency: '£',
    price: 1500,
    discount_price: 1400,
    before_price: '',
    after_price: '',
    latitude: 40.712776,
    longitude: -74.005974,
    area: 85,
    exterior_area: 10,
    country: 'United States',
    state: 'New York',
    city: 'New York',
    address: '456 Elm St, New York',
    zip_code: '10001',
    ref_id: 'REF002',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '58',
    type: 'Villa',
    status: 'For Sale',
    title: 'Luxurious Beachfront Villa',
    description: 'A stunning villa with a private beach.',
    rooms: 7,
    bedrooms: 5,
    bathrooms: 4,
    currency: '$',
    price: 1500000,
    discount_price: 1450000,
    before_price: '',
    after_price: '',
    latitude: 25.276987,
    longitude: 55.296249,
    area: 450,
    exterior_area: 200,
    country: 'United Arab Emirates',
    state: 'Dubai',
    city: 'Dubai',
    address: 'Palm Jumeirah, Dubai',
    zip_code: '',
    ref_id: 'REF003',
    is_map_enabled: true,
    gallery_images: [
      '/assets/properties/property.png',
      '/assets/properties/property.png',
      '/assets/properties/property.png',
    ],
  },
  {
    id: '59',
    type: 'Cottage',
    status: 'For Sale',
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage surrounded by nature.',
    rooms: 4,
    bedrooms: 2,
    bathrooms: 2,
    currency: '€',
    price: 250000,
    discount_price: 240000,
    before_price: '',
    after_price: '',
    latitude: 48.856613,
    longitude: 2.352222,
    area: 120,
    exterior_area: 100,
    country: 'France',
    state: 'Île-de-France',
    city: 'Paris',
    address: '789 Oak St, Paris',
    zip_code: '75001',
    ref_id: 'REF004',
    is_map_enabled: true,
    gallery_images: ['/assets/properties/property.png'],
  },
];
